%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% STAGE 1 MATLAB BASELINE THERMAL MODEL CODE PACKAGE
% Project: FPGA-Accelerated Battery Thermal Digital Twin for Real-Time
%          Safety Prediction
% Author: Frank Ouma
%
% This code package contains the three MATLAB files required for Stage 1:
%
%   1. matlab/baseline_thermal_model.m
%   2. matlab/run_baseline_simulation.m
%   3. matlab/export_baseline_results.m
%
% The code is written as a professional first baseline model for GitHub.
% It implements a lumped thermal battery model based on the heat balance:
%
%   m * Cp * dT/dt = I^2 * R - hA * (T - Tamb)
%
% This model is intentionally simple. It provides the first scientific
% baseline before higher-fidelity COMSOL modeling, surrogate model training,
% quantization, and FPGA implementation.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FILE 1: matlab/baseline_thermal_model.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function results = baseline_thermal_model(params)
%BASELINE_THERMAL_MODEL Simulates a lumped battery thermal model.
%
%   results = baseline_thermal_model(params)
%
%   This function models battery temperature evolution over time using a
%   first-order lumped thermal energy balance. The battery is treated as a
%   single thermal mass with one average temperature. Heat is generated by
%   electrical losses and removed through a simplified cooling term.
%
%   Governing equation:
%
%       m * Cp * dT/dt = Q_gen - Q_cool
%
%   where:
%       Q_gen  = I^2 * R
%       Q_cool = hA * (T - Tamb)
%
%   Inputs:
%       params.mass_kg                  Battery mass in kilograms
%       params.specific_heat_J_per_kgK  Battery specific heat capacity
%       params.internal_resistance_ohm  Battery internal resistance
%       params.cooling_hA_W_per_K       Lumped cooling coefficient
%       params.ambient_temp_C           Ambient temperature in Celsius
%       params.initial_temp_C           Initial battery temperature in Celsius
%       params.current_profile_A        Current profile vector in amperes
%       params.time_step_s              Simulation time step in seconds
%       params.total_time_s             Total simulation time in seconds
%       params.safe_limit_C             Safe temperature threshold
%       params.warning_limit_C          Warning temperature threshold
%       params.critical_limit_C         Critical temperature threshold
%
%   Output:
%       results                         Structure containing time, current,
%                                       temperature, heat generation,
%                                       cooling heat, temperature rate,
%                                       and thermal state.
%
%   Modeling assumptions:
%       1. The battery is represented by one average temperature.
%       2. Internal heat generation is approximated using I^2R losses.
%       3. Cooling is represented by a lumped hA coefficient.
%       4. Ambient temperature remains constant during the simulation.
%       5. No cell-to-cell temperature gradient is modeled at this stage.
%       6. No fluid dynamics, pressure drop, or cooling channel geometry is
%          modeled at this stage.
%
%   This baseline model is used for early physics understanding and later
%   comparison against COMSOL, surrogate ML models, and FPGA outputs.

    validate_required_parameters(params);

    dt = params.time_step_s;
    total_time = params.total_time_s;

    time_s = (0:dt:total_time)';
    n_steps = length(time_s);

    current_A = prepare_current_profile(params.current_profile_A, n_steps);

    temperature_C = zeros(n_steps, 1);
    heat_generated_W = zeros(n_steps, 1);
    heat_removed_W = zeros(n_steps, 1);
    net_heat_W = zeros(n_steps, 1);
    temperature_rate_C_per_s = zeros(n_steps, 1);
    thermal_state = strings(n_steps, 1);

    temperature_C(1) = params.initial_temp_C;

    thermal_mass_J_per_K = params.mass_kg * params.specific_heat_J_per_kgK;

    for k = 1:n_steps
        I = current_A(k);
        T = temperature_C(k);

        heat_generated_W(k) = I^2 * params.internal_resistance_ohm;
        heat_removed_W(k) = params.cooling_hA_W_per_K * (T - params.ambient_temp_C);
        net_heat_W(k) = heat_generated_W(k) - heat_removed_W(k);
        temperature_rate_C_per_s(k) = net_heat_W(k) / thermal_mass_J_per_K;
        thermal_state(k) = classify_thermal_state(T, params);

        if k < n_steps
            temperature_C(k + 1) = T + temperature_rate_C_per_s(k) * dt;
        end
    end

    results = struct();
    results.time_s = time_s;
    results.current_A = current_A;
    results.temperature_C = temperature_C;
    results.heat_generated_W = heat_generated_W;
    results.heat_removed_W = heat_removed_W;
    results.net_heat_W = net_heat_W;
    results.temperature_rate_C_per_s = temperature_rate_C_per_s;
    results.thermal_state = thermal_state;

    results.summary = generate_summary(results, params);
    results.params = params;
end


function validate_required_parameters(params)
%VALIDATE_REQUIRED_PARAMETERS Checks that the required fields exist and are valid.

    required_fields = {
        'mass_kg', ...
        'specific_heat_J_per_kgK', ...
        'internal_resistance_ohm', ...
        'cooling_hA_W_per_K', ...
        'ambient_temp_C', ...
        'initial_temp_C', ...
        'current_profile_A', ...
        'time_step_s', ...
        'total_time_s', ...
        'safe_limit_C', ...
        'warning_limit_C', ...
        'critical_limit_C'
    };

    for i = 1:length(required_fields)
        field_name = required_fields{i};
        if ~isfield(params, field_name)
            error('Missing required parameter: %s', field_name);
        end
    end

    if params.mass_kg <= 0
        error('mass_kg must be greater than zero.');
    end

    if params.specific_heat_J_per_kgK <= 0
        error('specific_heat_J_per_kgK must be greater than zero.');
    end

    if params.internal_resistance_ohm < 0
        error('internal_resistance_ohm cannot be negative.');
    end

    if params.cooling_hA_W_per_K < 0
        error('cooling_hA_W_per_K cannot be negative.');
    end

    if params.time_step_s <= 0
        error('time_step_s must be greater than zero.');
    end

    if params.total_time_s <= 0
        error('total_time_s must be greater than zero.');
    end

    if params.safe_limit_C >= params.warning_limit_C
        error('safe_limit_C must be lower than warning_limit_C.');
    end

    if params.warning_limit_C >= params.critical_limit_C
        error('warning_limit_C must be lower than critical_limit_C.');
    end
end


function current_A = prepare_current_profile(current_input, n_steps)
%PREPARE_CURRENT_PROFILE Creates a current vector matching the simulation length.
%
%   If the input is a scalar, the same current is used for the full
%   simulation. If the input is a vector, it must either match the number of
%   time steps or it will be interpolated to match the simulation length.

    if isscalar(current_input)
        current_A = current_input * ones(n_steps, 1);
        return;
    end

    current_input = current_input(:);

    if length(current_input) == n_steps
        current_A = current_input;
        return;
    end

    original_index = linspace(1, n_steps, length(current_input));
    target_index = 1:n_steps;
    current_A = interp1(original_index, current_input, target_index, 'linear', 'extrap')';
end


function state = classify_thermal_state(temperature_C, params)
%CLASSIFY_THERMAL_STATE Classifies temperature into safe, warning, or critical.

    if temperature_C < params.safe_limit_C
        state = "SAFE";
    elseif temperature_C < params.warning_limit_C
        state = "WATCH";
    elseif temperature_C < params.critical_limit_C
        state = "WARNING";
    else
        state = "CRITICAL";
    end
end


function summary = generate_summary(results, params)
%GENERATE_SUMMARY Produces key simulation summary values.

    [max_temp_C, max_index] = max(results.temperature_C);
    final_temp_C = results.temperature_C(end);
    max_temperature_rate_C_per_s = max(results.temperature_rate_C_per_s);
    average_heat_generated_W = mean(results.heat_generated_W);
    average_heat_removed_W = mean(results.heat_removed_W);

    critical_indices = find(results.temperature_C >= params.critical_limit_C, 1, 'first');
    warning_indices = find(results.temperature_C >= params.warning_limit_C, 1, 'first');

    if isempty(warning_indices)
        time_to_warning_s = NaN;
    else
        time_to_warning_s = results.time_s(warning_indices);
    end

    if isempty(critical_indices)
        time_to_critical_s = NaN;
    else
        time_to_critical_s = results.time_s(critical_indices);
    end

    summary = struct();
    summary.max_temp_C = max_temp_C;
    summary.time_of_max_temp_s = results.time_s(max_index);
    summary.final_temp_C = final_temp_C;
    summary.max_temperature_rate_C_per_s = max_temperature_rate_C_per_s;
    summary.average_heat_generated_W = average_heat_generated_W;
    summary.average_heat_removed_W = average_heat_removed_W;
    summary.time_to_warning_s = time_to_warning_s;
    summary.time_to_critical_s = time_to_critical_s;
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FILE 3: matlab/export_baseline_results.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function export_baseline_results(results, csv_file, summary_file)
%EXPORT_BASELINE_RESULTS Exports simulation results and summary report.
%
%   export_baseline_results(results, csv_file, summary_file)
%
%   This function writes the Stage 1 baseline thermal model outputs into a
%   CSV dataset and creates a text summary file for documentation.
%
%   Inputs:
%       results       Structure returned by baseline_thermal_model
%       csv_file      Full path to output CSV file
%       summary_file  Full path to output summary text file
%
%   CSV output columns:
%       time_s
%       current_A
%       temperature_C
%       heat_generated_W
%       heat_removed_W
%       net_heat_W
%       temperature_rate_C_per_s
%       thermal_state
%
%   The exported CSV becomes the first dataset artifact in the GitHub
%   project and provides a reference for later COMSOL and surrogate model
%   validation.

    output_table = table();
    output_table.time_s = results.time_s;
    output_table.current_A = results.current_A;
    output_table.temperature_C = results.temperature_C;
    output_table.heat_generated_W = results.heat_generated_W;
    output_table.heat_removed_W = results.heat_removed_W;
    output_table.net_heat_W = results.net_heat_W;
    output_table.temperature_rate_C_per_s = results.temperature_rate_C_per_s;
    output_table.thermal_state = results.thermal_state;

    writetable(output_table, csv_file);

    write_summary_report(results, summary_file);
end


function write_summary_report(results, summary_file)
%WRITE_SUMMARY_REPORT Writes a professional text summary of the run.

    fid = fopen(summary_file, 'w');

    if fid == -1
        error('Unable to create summary file: %s', summary_file);
    end

    cleanup_object = onCleanup(@() fclose(fid));

    fprintf(fid, 'Stage 1 Baseline Thermal Model Summary\n');
    fprintf(fid, 'Project: FPGA-Accelerated Battery Thermal Digital Twin for Real-Time Safety Prediction\n');
    fprintf(fid, 'Author: Frank Ouma\n');
    fprintf(fid, '\n');

    fprintf(fid, 'Model Purpose\n');
    fprintf(fid, 'This simulation represents the first simplified thermal baseline for the project.\n');
    fprintf(fid, 'The battery is treated as a single lumped thermal mass with one average temperature.\n');
    fprintf(fid, 'The model estimates temperature rise from electrical heat generation and heat removal through cooling.\n');
    fprintf(fid, '\n');

    fprintf(fid, 'Governing Heat Balance\n');
    fprintf(fid, 'm * Cp * dT/dt = I^2 * R - hA * (T - Tamb)\n');
    fprintf(fid, '\n');

    fprintf(fid, 'Main Parameter Values\n');
    fprintf(fid, 'Battery mass: %.4f kg\n', results.params.mass_kg);
    fprintf(fid, 'Specific heat capacity: %.4f J/kg.K\n', results.params.specific_heat_J_per_kgK);
    fprintf(fid, 'Internal resistance: %.6f ohm\n', results.params.internal_resistance_ohm);
    fprintf(fid, 'Cooling hA: %.4f W/K\n', results.params.cooling_hA_W_per_K);
    fprintf(fid, 'Ambient temperature: %.4f degC\n', results.params.ambient_temp_C);
    fprintf(fid, 'Initial temperature: %.4f degC\n', results.params.initial_temp_C);
    fprintf(fid, 'Simulation time step: %.4f s\n', results.params.time_step_s);
    fprintf(fid, 'Total simulation time: %.4f s\n', results.params.total_time_s);
    fprintf(fid, '\n');

    fprintf(fid, 'Simulation Results\n');
    fprintf(fid, 'Maximum temperature: %.4f degC\n', results.summary.max_temp_C);
    fprintf(fid, 'Time of maximum temperature: %.4f s\n', results.summary.time_of_max_temp_s);
    fprintf(fid, 'Final temperature: %.4f degC\n', results.summary.final_temp_C);
    fprintf(fid, 'Maximum temperature rise rate: %.8f degC/s\n', results.summary.max_temperature_rate_C_per_s);
    fprintf(fid, 'Average heat generated: %.4f W\n', results.summary.average_heat_generated_W);
    fprintf(fid, 'Average heat removed: %.4f W\n', results.summary.average_heat_removed_W);

    if isnan(results.summary.time_to_warning_s)
        fprintf(fid, 'Time to warning threshold: Not reached\n');
    else
        fprintf(fid, 'Time to warning threshold: %.4f s\n', results.summary.time_to_warning_s);
    end

    if isnan(results.summary.time_to_critical_s)
        fprintf(fid, 'Time to critical threshold: Not reached\n');
    else
        fprintf(fid, 'Time to critical threshold: %.4f s\n', results.summary.time_to_critical_s);
    end

    fprintf(fid, '\n');
    fprintf(fid, 'Engineering Interpretation\n');
    fprintf(fid, 'The result provides the first reference trend for battery temperature evolution.\n');
    fprintf(fid, 'If heat generation exceeds heat removal, temperature rises.\n');
    fprintf(fid, 'If cooling becomes strong enough to balance heat generation, temperature approaches a steady value.\n');
    fprintf(fid, 'This baseline result will later be compared with high-fidelity COMSOL simulation data and surrogate model predictions.\n');
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% OPTIONAL README NOTE FOR CODE USAGE
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Recommended command to run from MATLAB:
%
%   cd battery-thermal-fpga-digital-twin/matlab
%   run_baseline_simulation
%
% Expected output after successful execution:
%
%   1. dataset/baseline/matlab_baseline_results.csv
%   2. reports/stage_01_baseline_summary.txt
%   3. figures/matlab_baseline/temperature_vs_time.png
%   4. figures/matlab_baseline/heat_generated_vs_time.png
%   5. figures/matlab_baseline/heat_removed_vs_time.png
%   6. figures/matlab_baseline/net_heat_vs_time.png
%   7. figures/matlab_baseline/current_profile_vs_time.png
%
% After running the code, commit the generated files to GitHub:
%
%   git add matlab docs dataset figures reports README.md
%   git commit -m "Add Stage 1 MATLAB baseline thermal model"
%   git push
